//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/ag/urethane.html
halflife.wad
liquids.wad
decals.wad
sprites/fire.spr
models/palmtree.mdl
sound/ambience/lv_neon.wav
models/pred_plant.mdl
sound/ambience/urethane.wav
sound/ambience/vehicle3.wav
gfx/env/nightwalker-id256_bk.tga
gfx/env/nightwalker-id256_dn.tga
gfx/env/nightwalker-id256_ft.tga
gfx/env/nightwalker-id256_lf.tga
gfx/env/nightwalker-id256_rt.tga
gfx/env/nightwalker-id256_up.tga
maps/urethane.bsp
maps/urethane.txt
